### ISSUE TITLE
Add tutorial for single subview

### ISSUE THREAD

**Issue by JaydenIrwin** [GeorgeElsham/ViewExtractor#1]
This is not a code change request, just a change to the README. I think it is worth noting, for a container with only 1 view in it (maybe a ForEach() or any other view), you must add another init() that looks like this:

`init<Content: View>(@ViewBuilder content: () -> Content) {
        self.views = [AnyView(content())]
}`

**Comment by GeorgeElsham** [comment]
Didn't think of that case, thank you! The README has been updated.
