### ISSUE TITLE
Extract one view

### ISSUE THREAD

**Issue by ekerik220** [GeorgeElsham/ViewExtractor#3]
First of all, thank you for creating this. It's very helpful.

I'm trying to reimplement SwiftUI's List using a UITableView since List is still very limited. Do you think there is any way to extract a single view from the tuple without loading all of the views?  The issue I'm having is that running .getViews loads all of the views at once, but I'd like to let UITableView request views as it needs them.

I'm going to keep studying the code to try and find a way to do this, but I figured I'd ask in the meantime!

Thanks again.

**Edit:** 
It seems like it might be possible to return an array of view creators: `[() -> AnyView]`, give that to UITableView, and let UITableView call the function at the index it needs for the view. Not sure if that's a good way to go about it. I'm still pretty new to Swift in general though and struggling to get it working generically. As just a really messy test I modified part of the code and watched what happens in the debugger:

```
public extension TupleView {
    var views: [AnyView] {
        let children = Mirror(reflecting: value).children

        // Test code
        let map = children.map { $0.value }
        var array: [() -> ModifiedContent<Teller, _FrameLayout>] = []
        map.forEach {
            let mirror = Mirror(reflecting: $0)
            if let data = mirror.descendant("data") as? Range<Int>,
               let content = mirror.descendant("content") as? (Int) -> ModifiedContent<Teller, _FrameLayout> {
                let z = data.map { data in { content(data) } }
                array.append(contentsOf: z)
            }
        }
        let test = array[5]()

        return children.flatMap { ViewExtractor.views(from: $0.value) }
    }
}

TableView {
            ForEach(0..<5) { index in
                Teller(index: index)
                    .frame(width: 100, height: 100)
            }
            ForEach(5..<5000) { index in
                Teller(index: index)
                    .frame(width: 100, height: 100)
            }
        }
```
This is creating a flat array of 5005 functions that all create Teller views (just a tiny view I made for testing). Memory usage seems to be pretty much the same regardless of if I have 5 views (functions) or 5000, so maybe something like this could work.

I think I'll try putting this in something like .getViewCreators() or something, and try to get it working generically. Not sure if this is a good way to go about what I'm trying to accomplish. Let me know if you can think of a better solution!

**Comment by GeorgeElsham** [comment]
Thank you @ekerik220! Sounds like a good suggestion - I'll do some experimenting and see if I can get it working well.

**Comment by GeorgeElsham** [comment]
Similar solution implemented: https://github.com/GeorgeElsham/ViewExtractor/pull/4
