### ISSUE TITLE
if statement creates a view even if false

### ISSUE THREAD

**Issue by JetForMe** [GeorgeElsham/ViewExtractor#5]
I'm using ViewExtractor to create a divided stack, much like your Readme example. The problem is, I have a stack with a conditional view:

```swift
if condition {
    VStack { ... }
}
```

If `condition` is false, ViewExtractor still gets a view in the views array, a complicated optional view:

```
▿ AnyView
  ▿ storage : <AnyViewStorage<Optional<VStack…(the rest of my view hierarchy)>>>
```

I don't know how to test if one of these is actually empty, so as to not draw the divider.

**Comment by GeorgeElsham** [comment]
Fixed in [this](https://github.com/GeorgeElsham/ViewExtractor/commit/09cc1e7bf7d1860b92b151bb0bf06ec25a9e9162) commit. Thank you!

**Comment by JetForMe** [comment]
Nice! For the life of me I could _not_ figure out how to do that test.

Honestly, I feel like ResultBuilders are not as refined as they should be.

Thank you!

**Comment by GeorgeElsham** [comment]
@JetForMe To be honest we shouldn't really be digging into the views - but in rare cases it can be useful, which is why I made this repo. Glad you find it useful!

**Comment by JetForMe** [comment]
For sure! Precisely your example use.
