### ISSUE TITLE
Extra views from group

### ISSUE THREAD

**Issue by ynnckcmprnl** [GeorgeElsham/ViewExtractor#9]
Any plans to extract the Views from a Group? Right now a Group is treated as a single View by ViewExtractor.
Apple's List does extract the Views inside a Group, comparable to the ForEach behaviour.

The upside of extracting Views form a Group is that it allows to "bypass" the max 10 Views limit of @ViewBuilder.

Apple's behaviour:
<img width="280" alt="Screenshot 2022-11-17 at 13 09 58" src="https://user-images.githubusercontent.com/690119/202442604-d6922430-8431-4920-8eb4-bd9f669096bb.png">
<img width="477" alt="Screenshot 2022-11-17 at 13 09 40" src="https://user-images.githubusercontent.com/690119/202442619-68698ffb-1275-4c36-a6fc-5682997cf9f9.png">

**Comment by GeorgeElsham** [comment]
Hi @ynnckcmprnl, thanks for the issue.

Does #10 fix the issue?

**Comment by GeorgeElsham** [comment]
Note - it is a major API change so check the README on examples. The new code is based on the idea from [this blog](https://movingparts.io/variadic-views-in-swiftui), which is much more robust than my previous solution of using reflection and accounting for edge cases such as this.

**Comment by ynnckcmprnl** [comment]
Brilliant, I can confirm the PR has the same behaviour as List.
Thanks!

**Comment by GeorgeElsham** [comment]
See release 2.0.0 on main branch
